# -*- coding: utf-8 -*-
"""indicium_healthcare_ai_poc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gJZaRFeS8cSvXIMo0dVELlE0ZaCk4lGI
"""

# -*- coding: utf-8 -*-
"""
Artificial Intelligence Engineer Certification - SRAG Agent PoC
Orquestrador LangGraph para análise de dados do DATASUS.
"""
import warnings
warnings.filterwarnings('ignore')

import os
import sqlite3
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime, timedelta

# Imports de IA e Agentes
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.tools import tool
from langchain_core.messages import HumanMessage, SystemMessage
from langgraph.graph import StateGraph, MessagesState, START, END
from langgraph.prebuilt import ToolNode
from duckduckgo_search import DDGS

# ==========================================
# 1. CONFIGURAÇÃO DO MODELO
# ==========================================
def configurar_llm():
    """Recupera a chave da API de forma robusta e inicializa o modelo."""
    api_key = os.environ.get("GOOGLE_API_KEY")

    if not api_key:
        try:
            from google.colab import userdata
            api_key = userdata.get('GOOGLE_API_KEY')
            os.environ["GOOGLE_API_KEY"] = api_key
        except ImportError:
            raise ValueError("Erro: GOOGLE_API_KEY não configurada. Defina a variável de ambiente antes de executar.")
        except Exception as e:
            print(f"[*] Erro de sincronia no Colab detectado: {e}")
            api_key = input("[*] Cole sua chave da API do Google aqui para continuar: ")
            os.environ["GOOGLE_API_KEY"] = api_key

    # Temperatura 0 garante respostas analíticas precisas
    return ChatGoogleGenerativeAI(model="gemini-3.6-flash", temperature=0)

# ==========================================
# 2. PRÉ-PROCESSAMENTO DE DADOS
# ==========================================
def preparar_banco_dados(path_2025, path_2026, path_db):
    """Lê os CSVs, limpa os dados sensíveis/ruídos e cria o banco SQLite."""
    print("[*] Iniciando pré-processamento estrito de dados...")

    df_2025 = pd.read_csv(path_2025, sep=';', low_memory=False)
    df_2026 = pd.read_csv(path_2026, sep=';', low_memory=False)
    df_bruto = pd.concat([df_2025, df_2026], ignore_index=True)

    colunas_alvo = [
        'DT_NOTIFIC', 'DT_SIN_PRI', 'SG_UF_NOT', 'ID_MUNICIP',
        'NU_IDADE_N', 'CS_SEXO', 'UTI', 'EVOLUCAO',
        'VACINA_COV', 'CLASSI_FIN'
    ]
    df_clean = df_bruto[colunas_alvo].copy()

    # Padronização de datas
    df_clean['DT_NOTIFIC'] = pd.to_datetime(df_clean['DT_NOTIFIC']).dt.tz_localize(None).dt.date
    df_clean['DT_SIN_PRI'] = pd.to_datetime(df_clean['DT_SIN_PRI']).dt.tz_localize(None).dt.date

    # Limpeza clínica (Removendo NaNs, códigos 9 e óbitos por outras causas)
    df_clean.dropna(subset=['UTI', 'EVOLUCAO', 'VACINA_COV'], inplace=True)
    df_clean = df_clean[df_clean['UTI'].isin([1.0, 2.0])]
    df_clean = df_clean[df_clean['EVOLUCAO'].isin([1.0, 2.0])]
    df_clean = df_clean[df_clean['VACINA_COV'].isin([1.0, 2.0])]

    # Tratamento da Classificação Final (4.0 = SRAG não especificada)
    df_clean['CLASSI_FIN'] = df_clean['CLASSI_FIN'].fillna(4.0)

    # Exportação
    with sqlite3.connect(path_db) as conexao:
        df_clean.to_sql('internacoes', conexao, if_exists='replace', index=False)

    print(f"[*] Banco de dados estruturado gerado com sucesso. Registros válidos: {df_clean.shape[0]}")

# ==========================================
# 3. FERRAMENTAS DO AGENTE (TOOLS)
# ==========================================
@tool
def consultar_metricas() -> dict:
    """Consulta o banco SQLite para calcular UTI, mortalidade, vacinação e taxa de aumento."""
    with sqlite3.connect('/content/srag_dados.db') as conexao:
        query_geral = '''
        SELECT
            COUNT(*) as total,
            SUM(CASE WHEN UTI = 1.0 THEN 1 ELSE 0 END) as uti_casos,
            SUM(CASE WHEN EVOLUCAO = 2.0 THEN 1 ELSE 0 END) as obitos,
            SUM(CASE WHEN VACINA_COV = 1.0 THEN 1 ELSE 0 END) as vacinados
        FROM internacoes
        '''
        df_geral = pd.read_sql(query_geral, conexao)
        total = int(df_geral['total'].iloc[0])

        df_datas = pd.read_sql('SELECT MAX(DT_NOTIFIC) as max_data FROM internacoes', conexao)
        data_max = pd.to_datetime(df_datas['max_data'].iloc[0])

        data_30d = (data_max - timedelta(days=30)).strftime('%Y-%m-%d')
        data_60d = (data_max - timedelta(days=60)).strftime('%Y-%m-%d')
        data_max_str = data_max.strftime('%Y-%m-%d')

        query_recentes = f"SELECT COUNT(*) as casos FROM internacoes WHERE DT_NOTIFIC BETWEEN '{data_30d}' AND '{data_max_str}'"
        query_anteriores = f"SELECT COUNT(*) as casos FROM internacoes WHERE DT_NOTIFIC BETWEEN '{data_60d}' AND '{data_30d}'"

        casos_30d = pd.read_sql(query_recentes, conexao)['casos'].iloc[0]
        casos_60d = pd.read_sql(query_anteriores, conexao)['casos'].iloc[0]
        taxa_aumento = ((casos_30d - casos_60d) / casos_60d) * 100 if casos_60d > 0 else 0

    return {
        "taxa_ocupacao_uti": f"{(df_geral['uti_casos'].iloc[0] / total) * 100:.1f}%",
        "taxa_mortalidade": f"{(df_geral['obitos'].iloc[0] / total) * 100:.1f}%",
        "taxa_vacinacao": f"{(df_geral['vacinados'].iloc[0] / total) * 100:.1f}%",
        "taxa_aumento_casos_30d": f"{taxa_aumento:.1f}%",
        "casos_recentes_30d": int(casos_30d)
    }

@tool
def gerar_graficos() -> str:
    """Gera gráficos de casos de SRAG dos últimos 30 dias e 12 meses."""
    with sqlite3.connect('/content/srag_dados.db') as conexao:
        df = pd.read_sql('SELECT DT_NOTIFIC FROM internacoes', conexao)

    df['DT_NOTIFIC'] = pd.to_datetime(df['DT_NOTIFIC'])
    data_max = df['DT_NOTIFIC'].max()

    # Gráfico 1: 30 dias
    df_30d = df[df['DT_NOTIFIC'] > (data_max - timedelta(days=30))]
    plt.figure(figsize=(10, 5))
    df_30d.groupby('DT_NOTIFIC').size().plot(kind='line', color='red', marker='o')
    plt.title('Casos de SRAG - Últimos 30 Dias')
    plt.ylabel('Número de Casos')
    plt.grid(True)
    plt.savefig('/content/grafico_30_dias.png')
    plt.close()

    # Gráfico 2: 12 meses
    df_12m = df[df['DT_NOTIFIC'] > (data_max - timedelta(days=365))].copy()
    df_12m['Mes_Ano'] = df_12m['DT_NOTIFIC'].dt.to_period('M')
    plt.figure(figsize=(10, 5))
    df_12m.groupby('Mes_Ano').size().plot(kind='bar', color='blue')
    plt.title('Casos de SRAG - Últimos 12 Meses')
    plt.ylabel('Número de Casos')
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig('/content/grafico_12_meses.png')
    plt.close()

    return "Gráficos 'grafico_30_dias.png' e 'grafico_12_meses.png' gerados com sucesso."

@tool
def buscar_noticias(query: str) -> str:
    """Busca notícias recentes na web para contextualização."""
    try:
        ddgs = DDGS()
        resultados = list(ddgs.text(query, region='br-tz', timelimit='m', max_results=3))
        contexto = "\n\n".join([f"Título: {r['title']}\nResumo: {r['body']}" for r in resultados])
        return contexto if contexto else "Nenhuma notícia relevante encontrada."
    except Exception as e:
        return f"Erro ao buscar notícias: {e}"

# ==========================================
# 4. ORQUESTRADOR LANGGRAPH
# ==========================================
def construir_grafo(llm_instance, tools_list):
    """Constrói e compila o fluxo do agente LangGraph."""
    llm_with_tools = llm_instance.bind_tools(tools_list)

    def agent_node(state: MessagesState):
        mensagens = state["messages"]
        if not any(isinstance(m, SystemMessage) for m in mensagens):
            sys_prompt = '''Você é um analista de dados de saúde sênior responsável por relatórios de SRAG.
            Siga rigorosamente estes passos:
            1. Chame 'consultar_metricas'.
            2. Chame 'gerar_graficos'.
            3. Chame 'buscar_noticias' com a query "Síndrome Respiratória Aguda Grave Brasil".
            4. Redija o relatório final estruturado contendo as métricas, análise contextual e confirmação visual.
            Mantenha um tom executivo, claro e direto.'''
            mensagens = [SystemMessage(content=sys_prompt)] + mensagens
        return {"messages": [llm_with_tools.invoke(mensagens)]}

    def should_continue(state: MessagesState):
        return "tools" if state["messages"][-1].tool_calls else END

    workflow = StateGraph(MessagesState)
    workflow.add_node("agent", agent_node)
    workflow.add_node("tools", ToolNode(tools_list))
    workflow.add_edge(START, "agent")
    workflow.add_conditional_edges("agent", should_continue, ["tools", END])
    workflow.add_edge("tools", "agent")

    return workflow.compile()

# ==========================================
# 5. EXECUÇÃO PRINCIPAL
# ==========================================
if __name__ == "__main__":
    # 1. Preparar Banco de Dados
    preparar_banco_dados('/content/INFLUD25-14-09-2026.csv', '/content/INFLUD26-14-09-2026.csv', '/content/srag_dados.db')

    # 2. Configurar LLM e Ferramentas
    llm = configurar_llm()
    ferramentas = [consultar_metricas, gerar_graficos, buscar_noticias]

    # 3. Compilar Grafo
    app = construir_grafo(llm, ferramentas)

    # 4. Executar Agente
    print("-" * 50)
    print("[*] Iniciando a orquestração do Agente LangGraph...")

    inputs = {"messages": [HumanMessage(content="Gere o relatório automatizado sobre o cenário atual de SRAG, com métricas, notícias recentes e os gráficos.")]}

    for output in app.stream(inputs, stream_mode="values"):
        last_msg = output["messages"][-1]

        if hasattr(last_msg, 'tool_calls') and last_msg.tool_calls:
            for tool_call in last_msg.tool_calls:
                print(f"[*] Agente solicitou execução da ferramenta: {tool_call['name']}...")

        elif last_msg.content:
            texto = last_msg.content[0]['text'] if isinstance(last_msg.content, list) else last_msg.content
            print("\n" + "="*50)
            print("📄 RELATÓRIO FINAL GERADO")
            print("="*50)
            print(texto)

            with open('/content/relatorio_final.md', 'w', encoding='utf-8') as f:
                f.write(texto)
            print("\n[*] O arquivo 'relatorio_final.md' foi gerado e salvo com sucesso na pasta!")